CREATE TABLE EMP_1(
EMP_NUM VARCHAR(3),
EMP_Lname VARCHAR(15),
EMP_Fname VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIBEDATE DATE,
JOB_CODE CHAR(3));

SELECT * FROM EMP_1 WHERE JOB_CODE = '502';
INSERT INTO EMP_1 (EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIBEDATE, JOB_CODE) VALUES ('21', 'Ronquillo', 'Jaira', 'M', '2003-08-21', '502');

DROP TABLE EMP_1
